language: node_js
node_js:
  - 10

script:
  - npm run build

deploy:
  - on:
      branch: master
    provider: script
    script: script/deploy --token="$NOW_TOKEN"

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh
