language: node_js
node_js:
  - 10

before_script:
  - echo 'TRAVIS_COMMIT:' "$TRAVIS_COMMIT"
  - now-github-url --ref "$TRAVIS_COMMIT"

script:
  - npm run build

deploy:
  - on:
      branch: master
    provider: script
    script: script/deploy --token="$NOW_TOKEN"
  - on:
      all_branches: true
    provider: script
    script: script/deploy-preview --token="$NOW_TOKEN"

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh
