language: node_js
node_js:
  - 10

script:
  - npm run build

deploy:
  - on:
      branch: master
      condition: -v NOW_TOKEN
    provider: script
    script: script/deploy --token="$NOW_TOKEN"
  - on:
      all_branches: true
    provider: script
    script: test -v NOW_TOKEN && script/deploy-preview --token="$NOW_TOKEN"

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh

env:
  global:
    # NOW_TOKEN
    - secure: cKoKp6ZC4S9yR4n9gdPhv7IP79ey6GLagJzRJnM6ic+MvRHvGqfmVABHaF3O3TmCskOaLSKo0zxiqVe6WQxOsibDKRkcwiZVrnK2if1YA/ZQnA2TKzsGzHS1eEZ4jaOcZltyYcar55pYPhMPWlj7pOJtsNYKar/WV0dfrD2Dy9LFJSvOQ1M1LchpA+9o9uEVz8gtGeMD6X21Wko03x4xKQbDB6bpQFteXKN6UGSrGr2hya385pIOpbM1avMtlURgTXPUDGttV9jwkWOpelUiIv9qYmMK4nvbcQzmXAFxonmW4dn2NrgpUgV/sGIohLHFBDEm3ouBL75Ew0ocpSQjSswV4n6kstbaXyB2WAgIKlGOKpj3lyh6EF2vrAG07KwxghbYAloJjX/oJlf/+gTuE+H9B8WHwpisrPdLW/lvX/CnUGInCMelI413CC6e9Tq4OrDi9eWMzdfPZfS+LPvd2VEgP1eAO9UX6VbgCbRIfqkiII8j2FCUMTNUwHsqLgv9mXcpsAB+EeFfEZGLZuDW3D1Wt4T/f7xPUpnsfqmryeONtm6ZQ7bFnYGwd9ylGw3cvJI+ph64TiMt2D7wogeltLwYT4AWX9IKtlJJGdNdiV85sJ7lP1NC3LnloRlogmHhktqRmhtTJxBHdahgE3rrv1H6sGPjr2Pe28wqN8FuT5E=
    - secure: l964A1f7LLSSJbhUmWFLZWSyfGKhohY8KzcMICBlsjCidpgT2el3H+ocQR4PTfAeHebQfkOkqjt76mYetKO1OuHne+UsrbbSV70FA3BNDZDUVMYwSJFCAlKz6mH6gHnBAxRB36wo5dUG7IIuKBLqW6oxMpxUnO6jrwDrShEk8pz+JDQYxN6NL6MAhPoilhzFrZWanaxItpSC3ZI47xYMaGAzkyyNEBDVs1H3LdvZsO27LeFq443yAt0FNxzCvOI8edGpAs88TdQmOxg9Qk+NEPokCZpV6nO/EIFPWu+ee25bMUzGjy5OcDY9WlsY/PRX/1YZCNiH8unB0GkTcURZfIR/k0oE2/3JEdYoJonm4y9IZ5AKWxYW47HP5mgRZeyVHkst1XJWnNKqDT8ANBsaepp8u6ihHxFCoIMqAiWQsjQrC1VFB/ewPk3lvosqMMDWl7XP3wL8eY0gwPh01rGGaKxUSboOUpnujn9fXj44l6ZOOEzwXPWVcpJdWJTGJjDQoI+xenuWrv/Qnz7bZRlEN8EovZA0Crhz++wPkdwj20CmgGlqhdPOWgU3EGBC2xz0nCH0B2eX8qIRA2F5zJb9BALJADLMaZZjkUL4/feRpHlRW9zhIpNxR24uPr93QEqKLBPQPPTAKTw965WcIC1qhhHskiWcD9iUh6wey8ADp8k=
