language: node_js
node_js:
  - 10

script:
  - npm run build

before_deploy:
  - npm install -g now now-github-url
  - echo "Now URL: $(now-github-url)"

deploy:
  - on:
      branch: master
    provider: script
    script: script/deploy --token="$NOW_TOKEN"
  - on:
      all_branches: true
    provider: script
    script: script/deploy-preview --token="$NOW_TOKEN"

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh
