language: node_js
node_js:
  - 10

script:
  - npm run build

deploy:
  - on:
      branch: master
      condition: -v NOW_TOKEN
    provider: script
    script: script/deploy --token="$NOW_TOKEN"
  - on:
      all_branches: true
      condition: TRAVIS_BRANCH != master
    provider: script
    script: test -v NOW_TOKEN && script/deploy-preview --token="$NOW_TOKEN"

notifications:
  slack: github:4OisIoqZYyMlWcw3hFtZgbmh

env:
  global:
    # NOW_TOKEN
    secure: cKoKp6ZC4S9yR4n9gdPhv7IP79ey6GLagJzRJnM6ic+MvRHvGqfmVABHaF3O3TmCskOaLSKo0zxiqVe6WQxOsibDKRkcwiZVrnK2if1YA/ZQnA2TKzsGzHS1eEZ4jaOcZltyYcar55pYPhMPWlj7pOJtsNYKar/WV0dfrD2Dy9LFJSvOQ1M1LchpA+9o9uEVz8gtGeMD6X21Wko03x4xKQbDB6bpQFteXKN6UGSrGr2hya385pIOpbM1avMtlURgTXPUDGttV9jwkWOpelUiIv9qYmMK4nvbcQzmXAFxonmW4dn2NrgpUgV/sGIohLHFBDEm3ouBL75Ew0ocpSQjSswV4n6kstbaXyB2WAgIKlGOKpj3lyh6EF2vrAG07KwxghbYAloJjX/oJlf/+gTuE+H9B8WHwpisrPdLW/lvX/CnUGInCMelI413CC6e9Tq4OrDi9eWMzdfPZfS+LPvd2VEgP1eAO9UX6VbgCbRIfqkiII8j2FCUMTNUwHsqLgv9mXcpsAB+EeFfEZGLZuDW3D1Wt4T/f7xPUpnsfqmryeONtm6ZQ7bFnYGwd9ylGw3cvJI+ph64TiMt2D7wogeltLwYT4AWX9IKtlJJGdNdiV85sJ7lP1NC3LnloRlogmHhktqRmhtTJxBHdahgE3rrv1H6sGPjr2Pe28wqN8FuT5E=
